linters-settings:
  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["*"]

issues:
  # Allows basic comments errors from `golint` to show up.
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - golint
    - govet
    - staticcheck
    - whitespace
